language : node_js
node_js :
 - stable
install:
 - npm install
script:
 - npm run ci
notifications:
  email:
    on_failure: always
deploy:
  provider: npm
  email: "mail@jamesthurley.com"
  api_key: "$NPM_AUTH_TOKEN"
  skip_cleanup: true
  on:
    branch: master
    tags: true
